# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5
dist: trusty
sudo: true

env:
  - TOXENV=py35

cache:
  - pip: true
  - directories:
    - $TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2
    - $TRAVIS_BUILD_DIR/solc-versions/solidity-0.4.2/build
    - $HOME/.ethash/

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - travis_retry sudo apt-get install -y ethereum
  - travis_retry pip install setuptools --upgrade
  - pip install -U tox
  - ./install_solidity.bash
  - export PATH=$PATH:$PWD/solc-versions/solidity-0.4.2/build/solc
  - solc --version
  - geth -h

before_script:
  - mkdir -p $HOME/.ethash
  - geth makedag 0 $HOME/.ethash

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}


